# Numerical Python - NumPy

In [4]:
#- Numpy used in Scientific Computing
#- Most useful feature of Numpy is n-dimensional array ( ndarray)
#- Three main benefits of Numpy over python List
#- 1. Less Memory
#- 2. Fast
#- 3. Convinient

Writing python is Fast; Loops an be slow
Numpy pushes its loops into compiled layer:
    - fast development time of python
    - fast execution time of the compiled code
In Numpy, number of dimensions of array is called "Rank" of the array 
Array class in numpy is called "ndarray"

Every ndarray has an associated dataTye ( dtype ) object

In [5]:
# Install Numpy
# pip install numpy

In [15]:
#importing Numpy package 
import numpy as np
import time 
import sys

## Benefits of Numpy over List

In [24]:
MAX_SIZE = 100000

list1 = range(MAX_SIZE)
list2 = range(MAX_SIZE)

array1 = np.arange(MAX_SIZE)
array2 = np.arange(MAX_SIZE)

#- find size of an element in list = sys.getsizeof(<int/float/..>)
#- find size of an element in array = <array>.itemsize

print("Size of list = {}".format(sys.getsizeof(5)*MAX_SIZE))
print("Size of array = {}".format(array1.size * array1.itemsize))

start_time = time.time()
list3 = [i+j for i,j in zip(list1,list2)]
end_time = time.time()
print("Time taken to add two lists of size {} = {}".format(MAX_SIZE,(end_time-start_time)))

start_time = time.time()
array3= array1 + array2
end_time = time.time()
print("Time taken to add two numpy arrays of size {} = {}".format(MAX_SIZE,(end_time-start_time)))

Size of list = 2800000
Size of array = 400000
Time taken to add two lists of size 100000 = 82.41787648200989
Time taken to add two numpy arrays of size 100000 = 0.10700607299804688


## Numpy One Dimesional Arrays

In [75]:
#- Using List
# array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

myList = [1,2,3,4,5]

npArray = np.array(myList)
print(type(npArray))
print(npArray)

npArray2 = np.array(myList,dtype=np.float64)
print(type(npArray2))
print(npArray2)

#- using arange method
#- arange([start,] stop[, step,], dtype=None)

npArange1 = np.arange(10) #- Extreme values are excluded
print(type(npArange1))
print(npArange1)

npArange2 = np.arange(11,20) #- [Start, Stop ] Extreme values are excluded
print(type(npArange2))
print(npArange2)

npArange3 = np.arange(20,40,2) #- [Start,Stop,Step] Extreme values are excluded
print(type(npArange3))
print(npArange3)

#- Creating from ndArray 
npComplex = np.array(npArray,dtype=np.complex64)
print(npComplex)

<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
[20 22 24 26 28 30 32 34 36 38]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


### Accessing Array Elements

In [76]:
#- Using Index Value
print(npArray[0])

#- Using indexing 
print(npArray2[:3])

#- Using Step Indexing 
print(npArray3[:4:2])

#- Reverese the Array 
print(npArray3[::-1])

#- Using Negative Indexing 
print(npArray[-4:-1])

1
[1. 2. 3.]
[1 3]
[5 4 3 2 1]
[2 3 4]


### Attributes of Numpy Array 

In [79]:
#- ndim - to know the dimension of the array
# <Array>.ndim
print("Dimension of array npArray = {}".format(npArray.ndim))

#- itemsize - to know size of an array element
#- nbytes - to know size of array 
print("Size of an array element = {}bytes and array total size = {}bytes".format(npArray.itemsize,npArray.size*npArray.itemsize))
print("Size of np Array = {}bytes".format(npArray.nbytes))

#- dtype - to know the data type of an array
print("Data Type of array npArray = {} ".format(npArray.dtype))

#- shape - to know the shape of the array
print("Shape of the Array = {}".format(npArray.shape))

#- T - Transpose 
print("Transpose of {} shape = {} =>  {} shape = {}".format(npArray,npArray.shape,npArray.T,npArray.T.shape))

#- size  - to know the size of an array 
print("Size of array = {}".format(npArray.size))

# imag - to print the imaginary part of the array 
print("Imaginary part of the Array = {}".format(npArray.imag))

# real - to print the real part of the array 
print("Real part of the Array = {}".format(npArray.real))

Dimension of array npArray = 1
Size of an array element = 4bytes and array total size = 20bytes
Size of np Array = 20bytes
Data Type of array npArray = int32 
Shape of the Array = (5,)
Transpose of [1 2 3 4 5] shape = (5,) =>  [1 2 3 4 5] shape = (5,)
Size of array = 5
Imaginary part of the Array = [0 0 0 0 0]
Real part of the Array = [1 2 3 4 5]


## N-Dimesional Arrays

In [95]:
#- zeros(shape, dtype=float, order='C')
#- create a n-dimensional array and with initialized values to ZERO
muld = np.zeros([3,3])
print(muld)

mul1 = np.zeros((3,2),dtype=int)
print(mul1)

mul2 = np.zeros((3,2),dtype=float,order='C')
print(mul2)

mul3 = np.zeros((3,2),dtype=float,order='F')
print(mul3)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0]
 [0 0]
 [0 0]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [99]:
#- np.ones(shape, dtype=None, order='C')
#- create a n-dimensional array and with initialized values to ONE

mul_1 = np.ones([4,4])
print(mul_1)

mul_2 = np.ones([3,3],dtype = int)
print(mul_2)

mul_3 = np.ones([4,5],dtype=complex,order='F')
print(mul_3)
#- create a n-dimensional array and with initialized values to ONE


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]]


In [101]:
#- np.full(shape, fill_value, dtype=None, order='C')
#- create a n-dimensional array and with initialized values to fill_value Argument

mul_full_1 = np.full([3,3],8)
print(mul_full_1)

mul_full_2 = np.full([2,3],7,dtype=complex)
print(mul_full_2)

[[8 8 8]
 [8 8 8]
 [8 8 8]]
[[7.+0.j 7.+0.j 7.+0.j]
 [7.+0.j 7.+0.j 7.+0.j]]


In [271]:
#- np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
print(np.eye(3))

#- Cumulative Sum 
r1 = np.arange(9).reshape(3,3)
print(r1)
print(np.cumsum(r1))
print(np.cumsum(r1,axis=0))
print(np.cumsum(r1,axis=1))

r2= np.empty(2) #- returns a new array of given shape and type with random values
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 0  1  3  6 10 15 21 28 36]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]
[1. 1.]


### arange - Similar to range() in Python 

In [111]:
#- arange([start,] stop[, step,], dtype=None)

init_list = np.arange(10)
print(init_list)

init_list_2 = np.arange(11,20) #- Extreme values are excluded 
print(init_list_2)

init_list_3 = np.arange(20,50,2) #- Extreme value excluded
print(init_list_3)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [115]:
#- np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
#- Return evenly spaced numbers over a specified interval.

sample_1 = np.linspace(1,5) # Gives 50 evenly spaced within 1 and 5 ( included )
print(sample_1)

sample_2= np.linspace(2,3,10) # Gives 10 evenly spaced values with in 2 and 3 ( included)
print(sample_2)

sample_3 = np.linspace(2,3,10,endpoint=False) # Gives 10 evenly spaced values with in 2 and 3 **( excluded )
print(sample_3)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]
[2.         2.11111111 2.22222222 2.33333333 2.44444444 2.55555556
 2.66666667 2.77777778 2.88888889 3.        ]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


### reshape() - Converting between 1D - ND

In [125]:
#- np.reshape(a, newshape, order='C')

re_list = np.arange(9)
print(re_list)
print("Attributes =>\n ndim = {}\n shape = {}\n".format(re_list.ndim,re_list.shape))
re_list = re_list.reshape(3,3)
print(re_list)
print("Attributes =>\n ndim = {}\n shape = {}\n".format(re_list.ndim,re_list.shape))

#- Making in a single step order 'C' - CStyle
re_list_2 = np.arange(11,20).reshape(3,3)
print(re_list_2)
print("Attributes =>\n ndim = {}\n shape = {}\n".format(re_list_2.ndim,re_list_2.shape))

#- order 'F' - Fortan
re_list_3 = np.arange(11,20).reshape((3,3),order='F')
print(re_list_3)
print("Attributes =>\n ndim = {}\n shape = {}\n".format(re_list_3.ndim,re_list_3.shape))

[0 1 2 3 4 5 6 7 8]
Attributes =>
 ndim = 1
 shape = (9,)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Attributes =>
 ndim = 2
 shape = (3, 3)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
Attributes =>
 ndim = 2
 shape = (3, 3)

[[11 14 17]
 [12 15 18]
 [13 16 19]]
Attributes =>
 ndim = 2
 shape = (3, 3)



In [146]:
%%html
<img src="axis_img.png",width=5,height=5>

In [172]:
print(re_list_3)

#- Min
print(np.min(re_list_3))        #- Gives minimum value of the array 
print(np.min(re_list_3,axis=0))  #- Gives minimum values along axis=0
print(np.min(re_list_3,axis=1))  #- Gives minimum values along axis=1

#- Max
print(np.max(re_list_3))        #- Gives maximum value of the array 
print(np.max(re_list_3,axis=0))  #- Gives maximum values along axis=0
print(np.max(re_list_3,axis=1))  #- Gives maximum values along axis=1

#- Sum
print(np.sum(re_list_3))        #- Gives Sum of the array 
print(np.sum(re_list_3,axis=0))  #- Gives Sum along axis=0
print(np.sum(re_list_3,axis=1))  #- Gives Sum along axis=1

#- Standard Deviation 
print("Standard Deviation = {}".format(np.std(sqrt_arr)))         #- Gives Standard Deviation of the array 
print("Standard Deviation = {}".format(np.std(sqrt_arr,axis=0)))  #- Gives Standard Deviation of the array along axis=0
print("Standard Deviation = {}".format(np.std(sqrt_arr,axis=1)))  #- Gives Standard Deviation of the array along axis=1

[[11 14 17]
 [12 15 18]
 [13 16 19]]
11
[11 14 17]
[11 12 13]
19
[13 16 19]
[17 18 19]
135
[36 45 54]
[42 45 48]
Standard Deviation = 5.163977794943222
Standard Deviation = [4.89897949 4.89897949 4.89897949]
Standard Deviation = [1.63299316 1.63299316 1.63299316]


In [173]:
#- Sqrt 
sqrt_arr = np.arange(9).reshape(3,3)*2
print(sqrt_arr)
print(np.sqrt(sqrt_arr))

#- Transpose
print("transponse of array = \n{} => \n{}".format(sqrt_arr,sqrt_arr.T))

#- Matrix product
print(sqrt_arr.dot(sqrt_arr.T)) # or
print(np.dot(sqrt_arr,sqrt_arr.T))

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[0.         1.41421356 2.        ]
 [2.44948974 2.82842712 3.16227766]
 [3.46410162 3.74165739 4.        ]]
transponse of array = 
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]] => 
[[ 0  6 12]
 [ 2  8 14]
 [ 4 10 16]]
[[ 20  56  92]
 [ 56 200 344]
 [ 92 344 596]]
[[ 20  56  92]
 [ 56 200 344]
 [ 92 344 596]]


In [178]:
#-Arithmetic Opetations
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1 2]
 [3 4]]


In [183]:
#- Relational Operators
print(a>b)
print(a<b)
print(a==b)
print(a!=b)
print(a>=b)
print(a<=b)

[[False False]
 [False False]]
[[ True  True]
 [ True  True]]
[[False False]
 [False False]]
[[ True  True]
 [ True  True]]
[[False False]
 [False False]]
[[ True  True]
 [ True  True]]


In [277]:
#- Binary Operations
num1 = 10
num2 = 11
print(np.bitwise_and(num1,num2)) #- bitwise AND on numbers

arr1 = np.array([2,8,125])
arr2 = np.array([3,3,115])
print(np.bitwise_and(arr1,arr2)) #- bitwise AND on Arrays
print(np.bitwise_or(arr1,arr2))  #- bitwsie OR on Arrays



10
[  2   0 113]
[  3  11 127]


### Iterating Arrays

In [194]:
arr_itr = np.linspace(1,10,9,endpoint=False).reshape(3,3)
print(arr_itr)
print(arr_itr.shape)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
(3, 3)


In [195]:
#- Method 1 - Iterate array to get each row and then iterate over each row to get each cell value
for row in arr_itr:
    for cell in row:
        print(cell)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


In [199]:
#- Method 2 - ravel()
for cell in np.ravel(arr_itr):
    print(cell)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


In [207]:
#- Method 3 - using flatten()
for cell in arr_itr.flatten():
    print(cell)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


In [206]:
#- Method 4 - using flat
for cell in arr_itr.flat:
    print(cell)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


In [272]:
#- Using nditer
#- Efficient Multi-Dimensional  Iterator object to iterate over array 
#- The order of iteration is choosen to match memory layout of an array ,without condidering a particular ordering
#- This can be seen by iterting over transpose of an array 

for cell in np.nditer(arr_itr):  #- CStyle 
    print(cell)
    
for cell in np.nditer(arr_itr,order='F'): #- Fortan Style
    print(cell)



1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
1.0
4.0
7.0
2.0
5.0
8.0
3.0
6.0
9.0


### Stacking Arrays


In [217]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
print(a)
print(b)
c = np.hstack((a,b))
d = np.vstack((a,b))
print("Horizontal Stack => \n{}".format(c))
print("Vertical Stack => \n{}".format(d))


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Horizontal Stack => 
[[1 2 5 6]
 [3 4 7 8]]
Vertical Stack => 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Splitting Arrays

In [224]:
h_res = np.hsplit(c,2)
print(h_res)

v_res = np.vsplit(d,4)
print(v_res)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


### Conditional Indexing

In [241]:
arr_new = np.linspace(1,3,5)
print("Original Array = {}".format(arr_new))
list_1 = [True,False,False,True,True]
print("Conditional Output = {}".format(arr_new[list_1]))
print("Conditional Output = {}".format(arr_new[arr_new>2]))

#- Set the Values to -1 which are greater then 2
arr_new[arr_new>2] = -1
print("Modified Array = {}".format(arr_new))

Original Array = [1.  1.5 2.  2.5 3. ]
Conditional Output = [1.  2.5 3. ]
Conditional Output = [2.5 3. ]
Modified Array = [ 1.   1.5  2.  -1.  -1. ]


### READ and WRITE from FILES

In [252]:
#- Write to a file
"""
np.savetxt(
    ['fname', 'X', "fmt='%.18e'", "delimiter=' '", "newline='\\n'", "header=''", 
    "footer=''", "comments='# '", 'encoding=None'],
)
"""
np.savetxt
a1 = np.linspace(1,10,endpoint=False).reshape(10,5)
np.savetxt("array_items.txt",a1,header="Arrar Items",footer="---END---")


In [254]:
#- Read from a file
""" 
np.loadtxt(
    ['fname', "dtype=<class 'float'>", "comments='#'", 'delimiter=None', 'converters=None', 
    'skiprows=0', 'usecols=None', 'unpack=False', 'ndmin=0', "encoding='bytes'"],
)
"""

a2 = np.loadtxt("array_items.txt")
print(a2)

[[1.   1.18 1.36 1.54 1.72]
 [1.9  2.08 2.26 2.44 2.62]
 [2.8  2.98 3.16 3.34 3.52]
 [3.7  3.88 4.06 4.24 4.42]
 [4.6  4.78 4.96 5.14 5.32]
 [5.5  5.68 5.86 6.04 6.22]
 [6.4  6.58 6.76 6.94 7.12]
 [7.3  7.48 7.66 7.84 8.02]
 [8.2  8.38 8.56 8.74 8.92]
 [9.1  9.28 9.46 9.64 9.82]]


### Broadcasting

Broadcasting is a set of rules by which universal functions operate on arrays of different sizes and/or dimensions

In [255]:
np.arange(3) + 5

#- [ 0 1 2 ] + [ 5 5 5] => [ 5 6 7 ] => 5 is broadcasted 

#- [ 0 1 2 ]  + [0 1 2 ] => [0 1 2]   [0 1 2]   [0 2 4]
#- [ 3 4 5 ]                [3 4 5] + [0 1 2] = [3 5 7]
#- [ 6 7 8 ]                [6 7 8]   [0 1 2]   [6 8 10]

array([5, 6, 7])

Broadcasting Rules:
------------------------------
1. If array shape differ, left pad the smaller shape 
2. If any of the dimensions does not match, broadcast the dimension with size=1
3. If neither of the dimensions is 1, raise an error